### ISSUE TITLE
Répartition des fichiers

### ISSUE THREAD

**Issue by zoah** [zoah/wildermyth-fr#1]
## Fichiers terminés
- interface
  - interface.properties [traduit]
- aspects
  - aspects.properties [traduit]
- errors
  - errors.properties (non traduit, pour l'instant)

## Fichiers en cours de traduction
- dynamic
  - dynamic.properties (Zoah)
- story
  - story.properties (Kharot)
- scenario
  - scenario.properties (Nix)

**Comment by Piohm** [comment]
Si personne n'est en train de le faire, je commence à traduire quelques comics dans text>effects. Je fais le dossier tutorial pour l'instant.
J'éditerai mon message au fur et à mesure.

**Comment by zoah** [comment]
La liste est sur le discord, désormais.
