### ISSUE TITLE
Demande d'accès en tant que contributeur

### ISSUE THREAD

**Issue by Onirim** [zoah/wildermyth-fr#3]
Hello,

J'ai envie de faire un peu de traduction pour ce merveilleux jeu. Je ne sais pas quel est le projet le plus avancé sur le net, je ne suis pas tombé sur une communauté de traduction, donc je viens prendre contact par ici pour voir s'il y a moyen de commencer quelque part. :)

PS : Je ne sais pas comment contacter quelqu'un autrement sur Github ^^

**Comment by Onirim** [comment]
PS : y a-t-il un canal où vous retrouver ? Discurd, Slack, Mattermost ou autre ?

**Comment by Piohm** [comment]
Wildermyth's Discord server: https://discord.gg/ZQcmPtf
(from https://www.wildermyth.com/)

**Comment by zoah** [comment]
Je viens de créer un serveur Discord pour faciliter les échanges. Je vous ai invité tous les deux !

**Comment by zoah** [comment]
Quant aux accès en tant que contributeur, je suis dessus en ce moment.
