### ISSUE TITLE
Termes spécifiques

### ISSUE THREAD

**Issue by Piohm** [zoah/wildermyth-fr#4]
Bonjour,

Merci beaucoup pour votre travail. J'aimerais contribuer à la traduction du jeu. J'ai vu votre répartition des fichiers entre contributeurs, je vais regarder ce qu'il reste à faire et je fork si j'avance un peu.
J'ai complété les entrées de la page du wiki sur les termes spécifiques. Soyez indulgent avec moi, il y a sans aucun doute de nombreuses imprécisions. Je vais refaire la liste dans un prochain post sans mes commentaires pour que ce soit plus facile à faire la mise à jour avec les mots que vous garderez.

Avez-vous déjà traduit *grayplane* ? Si oui, cela peut impacter les expressions qui utilise cet autre plan d'existence (pour le chasseur notamment). Pour emprunter à Donjons et Dragons, on peut proposer le *plan Éthéré*  ou le *plan de l'Ombre*. Si on garde le Plan Gris, cela reste neutre comme dans la VO mais cela perd de son côté magique je trouve.
Fait-on des mots-valise pour les sorts utilisant la magie ? 

### Personnages

- Interfusion

Cela a l'air d'être un néologisme formé sur inter- et _infusion_ / *fusion*. Je suis tout à fait d'accord pour le garder tel quel, mais je voulais ajouter qu'il faudra sans doute l'accorder comme un nom, ou comme un verbe (sur la base de *infuser*), s'il est utilisé dans une description ou un scénario.

### Campagne

- *Spellthread*

C'est une ressource utilisée pour fabriquer des objets. C'est la même utilisation que le *spelltread* dans World of Warcraft. Par exemple, *Brilliant Spellthread* ([lien wow wiki EN](https://www.wowhead.com/item=41602/brilliant-spellthread)) devient *Fil ensorcelé brillant* ([lien wow wiki FR](https://fr.wowhead.com/item=41602/fil-ensorcel%C3%A9-brillant)). Je serai d'avis d'utilisé ***Fil ensorcelé***.

- Heartwoods

Ce n'est pas un mot inventé, c'est l'intérieur du tronc, le bois de le plus dur. On l'appelle en français *[duramen](https://fr.wikipedia.org/wiki/Duramen)* (vocabulaire de menuisier), "bois de cœur" ou "bois parfait". Le mieux serait de garder ***Bois de cœur*** par similarité avec la VO.

### Capacités génériques

- Hardiness

***Robustesse*** ou *Solidité*. *Hardiesse* est vieilli en français.

Plusieurs exemple de traduction de *hardiness* : *[Robustesse de Cognefort](https://fr.wowhead.com/spell=165898/robustesse-de-cognefort), [Solidité](https://fr.wowhead.com/spell=20573/solidit%C3%A9)* dans WOW ; les nains sont *Bold and hardy*, *[Téméraires et robustes](https://www.aidedd.org/regles/races/nain/).*

- *Viciousness*

Il s'agit d'un bonus aux dégâts à l'attaque. Une "attaque malveillante" ne convient pas tout à fait. Dans la même veine, je propose ***Cruauté***, pour traduire le caractère violent du personnage et de son attaque, de la même manière que *Vicious Attack* devient [*Moquerie cruelle*](https://www.aidedd.org/dnd/sorts.php?vf=moquerie-cruelle) dans Donjons et Dragons. Alternativement, on peut considérer *Brutalité*.

### Capacités du guerrier

- Backslam

**[*Heurtoir*](https://fr.wowhead.com/spell=1464/heurtoir)**, *Repousser* est une compétence du guerrier dans Donjons et Dragons.

- _Battledance_

*Danse de Bataille* ressemble à une mauvaise traduction de *dance battle*, et c'est bien dommage. _Shadowdancer_ (classe de prestige, Donjons et Dragons 3.5) est traduit comme *Maître des ombres*, alors que la classe met l'accent sur la mobilité de la danse. C'est pourquoi je proposerais ***Danse de combat*** pour _Battledance_. Je pense que l'accent est mis sur l'agilité et non comme une danse galvanisante, auquel cas *Danse Guerrière* serait approprié.

- *Bloodrage*

***[Rage de sang](https://fr.wowhead.com/spell=142879/rage-de-sang)***

- *Broadswipes*

[Balayage](https://fr.wowhead.com/spell=106785/balayage), [***Grand balayage***](https://fr.wowhead.com/spell=6749/grand-balayage) (*Wide Swipe*), *[Balayage latéral](https://fr.wowhead.com/spell=58508/balayage-lat%C3%A9ral)* (*Side Swipe*). *Balayage* est aussi une compétence du guerrier dans Donjons et Dragons.

- *Engage*

C'est littéralement un *Taunt*, que l'on peut traduire par ***Provocation***. *Provocation* est aussi une compétence du guerrier dans Donjons et Dragons. 

- *Raider*

*[**Pilleur**](https://fr.wowhead.com/npc=39153/pilleur-dexcavations)*, *[Pillard](https://fr.wowhead.com/npc=131949/pillard-roncedos)*

- *Shieldshear*

*Shieldshear* enlève de l'armure, on détruit le bouclier de l'ennemi. De la même manière que [Fracasser l'armure](https://fr.wowhead.com/spell=65936/fracasser-armure#see-also-other) (*Sunder Armor*), ce serait ***Fracasser le bouclier*** (sinon *déchirer*, *entailler*, *cisailler*...)

- *Stalwart*

***Pilier***

- *Thundering Challenge*

***Défi retentissant*** si on veut garder le sens du bruit (plus proche de la VO) ; *Défi Intimidant* pour mieux illustrer la terreur (si l'idée de peur est moins ressentie en français).

- *Vigilance*

***Vigilance*** avec un *a* en français aussi.

- *Wolfcall*

[L'appel du loup](https://fr.wowhead.com/item=57371/%C3%A9crase-boue-de-lappel-du-loup?bonus=3631)

- *Zealous Leap*

[Bond Zélé](https://fr.wowhead.com/spell=123638/ru%C3%A9e-z%C3%A9l%C3%A9e)

### Capacités du chasseur

- *Ambush*

***Embuscade***

- *Archery*

***Archerie***

- *Flashcone*

***Éclair aveuglant***

- *Foxflight*

***Fuite du renard***

- *Jumpjaw*

***Mâchoire à ressort***

- *Quellingmoss*

***Mousse paralysante*** (étouffante)

- *Rogue*

***Roublard***

- *Silkstep*

***Pas de côté de soie*** (un peu long ?) ; *Enjambée de soie*

- *Thornfang*

***Morsure de la ronce***

- *Through Shot*

***Tir perforant***. Par peur de confondre avec la méchanique de piercing damage, on pourrait aussi l'appelé *Tir ajusté*.

- *Windwalk*

[***Marche du vent***](https://heroesofthestorm.com/fr-fr/heroes/samuro/#heroicAbilities--samuro)

### Capacités du mystique

- *Arches*

***Arches***

- *Compulsion*

***Compulsion***, Contrainte. 

- *Elementalist*

***Élémentaliste***

- *Humanist*

***Humaniste***

- *Ignite*

***Embrasement***

- *Indignance*

***Indignation***

- *Mythweaver*

***Tisseur*** et ***Tisseuse de mythes***. Si quelqu'un préfère les appeler Tisse-mythes, ça ne me dérange pas.

- *Natural Ally*

***Allié Naturel***

- Naturalist

***Naturaliste***

- *Openmind*

***Large d'esprit***, Large esprit. *Ouvre-esprit*, si on veut lui donner l'allure d'un sortilège. Ou encore *Largesprit* si on préfère les mots-valise.

- *Soulsplitting*

***Division de l'âme***. *[Scission d'âme](https://fr.wowhead.com/spell=322557/scission-d-%C3%A2me)*.

- *Spiritblade*

***Lame spirituelle*** (Spirit Blade, D&D)

**Comment by Piohm** [comment]
### Personnages

- Interfusion = Interfusion

- Stunt = Prouesse

### Campagne

- Mission = mission
- Battle = combat
- Legacy = Héritage
- Promote = promouvoir
- Spellthread = Fil ensorcelé
- Heartwoods = Bois de cœur
- Hides = Cuir

### Capacités génériques

- Aid = Secours
- Bard = Barde
- Bowmaster = Maître archer
- Endurance = endurance
- Hardiness = Robustesse
- Heroism = Héroïsme
- Long Reach = Longue portée
- Snakestrike = Frappe du serpent
- Viciousness = Cruauté
- Wisdow = Sagesse

### Capacités du guerrier

- Backslam = Heurtoir
- Battledance = Danse de combat
- Bloodrage = Rage de sang
- Broadswipes = Grand balayage
- Engage = Provocation
- Guardian = Gardien
- Inspiration = Inspiration
- Paladin = Paladin
- Raider = Pilleur
- Sentinel = Sentinelle
- Shieldshear = Fracasser le bouclier
- Stalwart = Pilier
- Thundering Challenge = Défi retentissant
- Vigilance = Vigilance
- Wolfcall L'appel du loup
- Zealous Leap = Bond Zélé

### Capacités du chasseur

- Ambush= Embuscade
- Archery = Archerie
- Ember Arrows = Flèches embrasées
- Flashcone = Éclair aveuglant
- Foxflight = Fuite du renard
- Jumpjaw = Mâchoire à ressort
- Quellingmoss = Mousse paralysante
- Rogue = Roublard
- Silkstep = Pas de côté de soie
- Thornfang = Morsure de la ronce
- Through Shot = Tir perforant
- Windwalk = Marche du vent

### Capacités du mystique

- Arches = Arches
- Compulsion = Compulsion
- Earthscribe = scribe terrestre
- Elementalist = Élémentaliste
- Humanist = Humaniste
- Ignite = Embrasement
- Indignance = Indignation
- Mythweaver = Tisseur et Tisseuse de mythes
- Natural Ally = Allié Naturel
- Naturalist = Naturaliste
- Openmind = Large d'esprit
- Soulsplitting = Division de l'âme
- Spiritblade = Lame spirituelle

**Comment by Piohm** [comment]
Des termes que je viens de rencontrer dans un comic qu'on rencontrera certainement dans les descriptions des compétences :
- Temp. Damage = Dégâts temp.
- Temp. Health = Santé temp.
- Blazes = Brasiers
- Double Stunt % =**Chance de Prouesse X2**, lire "Chance de Prouesse doublée" (il n'y a vraiment pas de place dans la case).

**Comment by zoah** [comment]
Tout d'abord, un grand merci pour tes efforts et ton implication !

Je vais t'accorder les droits de contributeur sur ce projet, ce qui te permettra de créer des branches et pousser ton propre contenu. Je vais également t'accorder le droit de modifier le wiki, que tu puisses y reporter tes contributions.

Pour le projet que tu as fourché, on peut passer par une PR.
