### ISSUE TITLE
Ligne directrice wiki

### ISSUE THREAD

**Issue by Piohm** [zoah/wildermyth-fr#5]
Bonjour,

Le jeu comporte l'emploi des pronoms neutres (they/them), en particulier dans les balises à choix multiples <roleName.selector:option1/option2/option3>
J'ai traduit ça par *iel/iels/lia* (il/eux/le au masculin, pour comparaison) et l'accord des participes passés et autres avec le point médian.

Comme Zoah précise dans cette page de wiki ([Ligne directrice](https://github.com/zoah/wildermyth-fr/wiki/Ligne-directrice)) quelques directions pour que l'on unifie la manière dont on traduit les textes, je pensais que ce serait bien de décider en amont des pronoms neutres, pour éviter de modifier tous les fichiers après coup.

**Comment by zoah** [comment]
Bonjour Piohm,

Lors de la traduction, je suis effectivement tombé sur le genre neutre. Selon s'il s'agit d'un personnage masculin, féminin ou non-binaire, les pronoms étaient respectivement he, she et they.

### Personnage non-binaire
J'ai opté pour "iel" en remplacement du they, étant donné qu'il concerne une personne non-binaire.
Dans le cas d'un adjectif ou d'un nom commun, j'ai utilisé l'écriture incluse pour faire ressortir la non-binarité.

### Plusieurs personnages de genre différents
L'emploi du iels n'est pas présent dans ce que j'ai traduit jusque-là. Généralement, la différenciation selon le genre se fait pour un personnage à la fois.

Note: Parfois, on parle de plusieurs personnages de genre différents (masculin, féminin, non-binaire). J'ai rencontré un seul cas comme celui-ci. J'ai appliqué un arbre (assez complexe) permettant de changer la phrase selon le genre.

### Le cas du lia
J'ai rencontré à un endroit la possibilité d'utiliser lia (que je ne connaissais pas avant). J'ai préféré changer la tournure de la phrase pour ne pas l'utiliser.

**Comment by zoah** [comment]
J'ai mis à jour le wiki en conséquence. Est-ce que ça répond à ta remarque ?

**Comment by Piohm** [comment]
Oui, parfait !
